### ISSUE TITLE
Request(?) for extending API

### ISSUE THREAD

**Issue by CaiMiao** [marcan/deresuteme#1]
Hello marcan, [superk589/CGSSGuide](https://github.com/superk589/CGSSGuide) is working on the colleague finder (仮：同僚募集センター),
and if it's allowed, we would prefer an auto method that collect users' center info with API in middle.
So I came here, left msg here and see if you have interest in it.

If everything goes fine, final process would look like this:
1. User registers ID in app
2. deresute.me deal with game API and proxy it
3. App looks for center through deresute.me
4. Upload result as SNAPSHOT to iCloud server  (Important, to reduce load of deresute.me)

5+. Other users get result (snapshots) from iCloud server

Please give some time look into it, ty in advance!

**Comment by superk589** [comment]
Colleague Finder is hosted on Apple's CloudKit, and CloudKit provides server to server api (I have to provide an api-key to allow the access). For more information [CloudKit Web Services Reference](https://developer.apple.com/library/content/documentation/DataManagement/Conceptual/CloudKitWebServicesReference/index.html)

So if you do have interest in it, I can provide the server api-key. (using it under the privacy policy of DereGuide) 

> 4. Upload result as SNAPSHOT to iCloud server (Important, to reduce load of deresute.me)
> 5. Other users get result (snapshots) from iCloud server

CloudKit have api for uploading from server to server, but not something like SNAPSHOT. So I think this can not be accomplished.

Colleague Finder now can only search for the profiles of who post it to CloudKit, and I can't validate the profile. DereGuide does not have the feature to validate this using an in-game api by now. However, deresuteme have a more convenience way to implement this feature. Users who want to post their profiles only need to commit their game-id, that's enough.

What does DereGuide really need is to get user profile by game-id, and a server gathering the CloudKit data and provide statistic api like "most popular centers of a period"

**Comment by marcan** [comment]
I'm not sure I grasp exactly what you want here. What API extension do you need? The support card info?

**Comment by marcan** [comment]
Well if it's support card info that you wanted I just added it to the API in a46249320 :)

**Comment by superk589** [comment]
In short:
1. I think CaiMiao's advise can not be accomplished.
2. DereGuide not really needs deresuteme to extend API. However, if you can extend for card info, that's good.

**Comment by superk589** [comment]
Good job. Amazing speed!
Thank you!

**Comment by marcan** [comment]
Just for the record, I changed the API slightly in subsequent commits (since the game server doesn't always return data, but I make it consistent and always do).

**Comment by CaiMiao** [comment]
It looks like superk have mistaken my mean :)
Anyway the card info api is what we need, thank you!

By the way, I learnt that you are suck a geek, keep your good work up!

**Comment by CaiMiao** [comment]
It looks like superk have mistaken my mean :)
Anyway the card info api is what we need, thank you!

By the way, I learnt that you are such a geek, keep your good work up!
