### ISSUE TITLE
API erroring out

### ISSUE THREAD

**Issue by Injabie3** [marcan/deresuteme#2]
Not sure if this is the right place, but images and json on deresute.me don't seem to be returning anymore. Seems like it's returning HTTP 500 for the json files at least.

**Comment by marcan** [comment]
Fixed. app_ver just needed a bump.

**Comment by Injabie3** [comment]
Not sure if I should reopen this, but I'm seeing something similar.

**Comment by marcan** [comment]
Should be fixed.

Note that I don't really have time to maintain this any more, so if things ever break in a major way it's unlikely I'll be able to fix it (this time it was easy).

**Comment by Injabie3** [comment]
Got it, thanks, appreciate keeping this running over the years!
